WebCinema01/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebCinema01.Models;

namespace WebCinema01.Controllers
{   
    public class ReservationsController : Controller
    {
        private CinemaContext context = new CinemaContext();

        //
        // GET: /Reservations/

        public ViewResult Index()
        {
            return View(context.Reservations.ToList());
        }

        //
        // GET: /Reservations/Details/5

        public ViewResult Details(int id)
        {
            Reservation reservation = context.Reservations.Single(x => x.ReservationId == id);
            return View(reservation);
        }

        //
        // GET: /Reservations/Create

        public ActionResult Create()
        {
            ViewBag.PossiblePrograms = context.Programs;
            ViewBag.PossibleHalls = context.Halls;
            ViewBag.PossiblePlaces = context.Places;
            return View();
        } 

        //
        // POST: /Reservations/Create

        [HttpPost]
        public ActionResult Create(Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                context.Reservations.Add(reservation);
                context.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.PossiblePrograms = context.Programs;
            ViewBag.PossibleHalls = context.Halls;
            ViewBag.PossiblePlaces = context.Places;
            return View(reservation);
        }
        
        //
        // GET: /Reservations/Edit/5
 
        public ActionResult Edit(int id)
        {
            Reservation reservation = context.Reservations.Single(x => x.ReservationId == id);
            ViewBag.PossiblePrograms = context.Programs;
            ViewBag.PossibleHalls = context.Halls;
            ViewBag.PossiblePlaces = context.Places;
            return View(reservation);
        }

        //
        // POST: /Reservations/Edit/5

        [HttpPost]
        public ActionResult Edit(Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                context.Entry(reservation).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PossiblePrograms = context.Programs;
            ViewBag.PossibleHalls = context.Halls;
            ViewBag.PossiblePlaces = context.Places;
            return View(reservation);
        }

        //
        // GET: /Reservations/Delete/5
 
        public ActionResult Delete(int id)
        {
            Reservation reservation = context.Reservations.Single(x => x.ReservationId == id);
            return View(reservation);
        }

        //
        // POST: /Reservations/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Reservation reservation = context.Reservations.Single(x => x.ReservationId == id);
            context.Reservations.Remove(reservation);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebCinema01/Views/Shared/_DisplayDetails.cshtml
@model IEnumerable<WebCinema01.Models.Movie>

<table>

    @foreach (var item in Model)
    {

        <tr>
            <b>Title</b>
            <br />
            @item.Title
        </tr>
        <br />
        <tr>
            <b>Director</b>
            @item.Director
        </tr>
        <br />
        <tr>
            <b>Actors</b>
            @item.Actors
        </tr>
        <br />
        <tr>
            <b>Description</b>
            @item.Description
        </tr>
        <br />
        <tr>
            <b>From Date</b>
            @String.Format("{0:d}", item.FromDate)
        </tr>
        <br />
        <tr>
            <b>To Date</b>
            @String.Format("{0:d}", item.ToDate)
        </tr>
        <br />
        <tr>
            @item.Picture
        </tr>
        <br />
        <tr>
            <b>Duration</b>
            @item.Duration
        </tr>

    }
</table>

WebCinema01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
</head>
<body>
    <header>
        <div class="container">
            <div class="row">
                <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
            </div>
            <div>

                <nav>
                    <ul id="menu" class="nav nav-pills span9 ">
                        <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                        <li class="active">@Html.ActionLink("About", "About", "Home")</li>
                        <li class="active">@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li class="active">@Html.ActionLink("Movies", "Index", "Movies")</li>
                        <li class="active">@Html.ActionLink("Reservation", "Index", "Reservations")</li>
                    </ul>
                    <div class="float-right">
                        <section id="login">
                            @Html.Partial("_LoginPartial")
                        </section>
                    </div>
                </nav>
            </div>
        </div>
    </header>
    <div id="container">
        @RenderSection("featured", required: false)
        <section class="container">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year -Cinema Application</p>
            </div>
        </div>
    </footer>

    @RenderSection("scripts", required: false)
</body>
</html>